//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mateusz_Cebrat_PUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anamnesis
    {
        public int patientID { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> height { get; set; }
        public string bloodType { get; set; }
        public string rh { get; set; }
        public string alcohol { get; set; }
        public string cigaretts { get; set; }
        public string medicines { get; set; }
        public string allergy { get; set; }
        public string chronicDiseases { get; set; }
        public string treatment { get; set; }
        public string additionalInformation { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
