//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mateusz_Cebrat_PUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurse
    {
        public int NurseID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    }
}
