//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mateusz_Cebrat_PUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int patientID { get; set; }
        public int visitID { get; set; }
        public int doctorID { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string pressure { get; set; }
        public Nullable<int> pulse { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public string symptoms { get; set; }
        public string diagnosis { get; set; }
        public string recommendations { get; set; }
        public string visitMedicines { get; set; }
        public string additionalVisitInformation { get; set; }
        public int mark { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
