//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mateusz_Cebrat_PUM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkInterview
    {
        public int patientID { get; set; }
        public string profession { get; set; }
        public string practisedProfession { get; set; }
        public string ocupationalDisease { get; set; }
        public string nuisance { get; set; }
        public string accidents { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
